[params]
  languageCode = "fr-fr"
  title = "Webgardener"
  subtitle = "On <i class="fa fa-heart" aria-hidden="true"></i> les logiciels libres"
  theme = "simple-a"
  disableKinds = ["RSS"]
  copyright = "webgardener"

